stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - shell
  only:
    - master
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "${DEPLOY_SSH_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - scp public/* ${DEPLOY_USER}:${DEPLOY_PASSWORD}@${DEPLOY_SERVER_IP}:${DEPLOY_PATH}
